env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-essential
  - airbnb
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - vue
rules: 
  no-console: 0
  import/extensions: 0
  import/no-unresolved: 0

